---
collections:
  - name: community.general
  - name: amazon.aws
  - name: community.aws
  - name: kubernetes.core
  - name: community.okd
  - name: ansible.utils
  - name: bitwarden.secrets
  - name: community.kubernetes