---

- name: Create OperatorGroup
  kubernetes.core.k8s:
    api_key: "{{ auth_results.openshift_auth.api_key }}"
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: global-operators
        namespace: openshift-operators
      spec: {}

- name: Install Service Mesh Operator
  kubernetes.core.k8s:
    api_key: "{{ auth_results.openshift_auth.api_key }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: servicemeshoperator
        namespace: openshift-operators
      spec:
        channel: stable
        name: servicemeshoperator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Install Serverless Operator
  kubernetes.core.k8s:
    api_key: "{{ auth_results.openshift_auth.api_key }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: serverless-operator
        namespace: openshift-operators
      spec:
        channel: stable
        name: serverless-operator
        source: redhat-operators
        sourceNamespace: openshift-marketplace

- name: Install Authorino Operator
  kubernetes.core.k8s:
    api_key: "{{ auth_results.openshift_auth.api_key }}"
    definition:
      apiVersion: operators.coreos.com/v1alpha1
      kind: Subscription
      metadata:
        name: authorino-operator
        namespace: openshift-operators
      spec:
        channel: stable
        name: authorino-operator
        source: community-operators
        sourceNamespace: openshift-marketplace