---
- name: Deploy Node Feature Discovery Operator
  hosts: localhost
  tasks:
    - name: Create NFD namespace
      k8s:
        api_version: v1
        kind: Namespace
        metadata:
          name: openshift-nfd

    - name: Create OperatorGroup
      k8s:
        api_version: operators.coreos.com/v1
        kind: OperatorGroup
        metadata:
          name: openshift-nfd
          namespace: openshift-nfd
        spec:
          targetNamespaces:
            - openshift-nfd

    - name: Create Subscription
      k8s:
        api_version: operators.coreos.com/v1alpha1
        kind: Subscription
        metadata:
          name: nfd-subscription
          namespace: openshift-nfd
        spec:
          channel: stable
          name: nfd
          source: community-operators
          sourceNamespace: openshift-marketplace

    - name: Wait for NFD Operator to be installed
      k8s_facts:
        api_version: operators.coreos.com/v1alpha1
        kind: ClusterServiceVersion
        namespace: openshift-nfd
      register: csv_facts
      until: >
        csv_facts.resources | selectattr('status.phase', 'equalto', 'Succeeded') | list | length > 0
      retries: 10
      delay: 30

    - name: Create NodeFeatureDiscovery Custom Resource
      k8s:
        api_version: nfd.openshift.io/v1
        kind: NodeFeatureDiscovery
        metadata:
          name: nfd-instance
          namespace: openshift-nfd
        spec:
          operand:
            image: quay.io/openshift/origin-node-feature-discovery:4.8
            imagePullPolicy: Always
          workerConfig:
            configData: |
              core:
                sleepInterval: 60s
              sources:
                cpu:
                  cpuid:
                    attributeWhitelist:
                      - "SSE"
                      - "SSE2"
                      - "SSE3"
                      - "SSE4.1"
                      - "SSE4.2"
                      - "SSSE3"